name: Rapid Cognition
favicon: null
layout_spectrum: 0.9185655610635877
typography_spectrum: 0.6211
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6082239930983633
  lightness: 0.9231297119986266
  saturation: 0.45500232349149883
  rhythmicContrast: 0.5058472468517721
purpose: []
